Use ubuntu 18.04 as a base image

diff --git a/19.03/Dockerfile b/19.03/Dockerfile
--- a/19.03/Dockerfile
+++ b/19.03/Dockerfile
@@ -1,15 +1,16 @@
-FROM alpine:3.11
+FROM ubuntu:18.04
 
-RUN apk add --no-cache \
-		ca-certificates \
+RUN apt-get update \
+    && apt-get install -y \
+        ca-certificates \
 # DOCKER_HOST=ssh://... -- https://github.com/docker/cli/pull/1014
-		openssh-client
+        openssh-client \
+        wget
 
 # set up nsswitch.conf for Go's "netgo" implementation (which Docker explicitly uses)
 # - https://github.com/docker/docker-ce/blob/v17.09.0-ce/components/engine/hack/make.sh#L149
 # - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
 # - docker run --rm debian:stretch grep '^hosts:' /etc/nsswitch.conf
-RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
 
 ENV DOCKER_CHANNEL stable
 ENV DOCKER_VERSION 19.03.5
@@ -18,35 +19,35 @@ ENV DOCKER_VERSION 19.03.5
 # (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
 
 RUN set -eux; \
-	\
+    \
 # this "case" statement is generated via "update.sh"
-	apkArch="$(apk --print-arch)"; \
-	case "$apkArch" in \
+    apkArch="$(uname -p)"; \
+    case "$apkArch" in \
 # amd64
-		x86_64) dockerArch='x86_64' ;; \
+        x86_64) dockerArch='x86_64' ;; \
 # arm32v6
-		armhf) dockerArch='armel' ;; \
+        armhf) dockerArch='armel' ;; \
 # arm32v7
-		armv7) dockerArch='armhf' ;; \
+        armv7) dockerArch='armhf' ;; \
 # arm64v8
-		aarch64) dockerArch='aarch64' ;; \
-		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
-	esac; \
-	\
-	if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
-		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
-		exit 1; \
-	fi; \
-	\
-	tar --extract \
-		--file docker.tgz \
-		--strip-components 1 \
-		--directory /usr/local/bin/ \
-	; \
-	rm docker.tgz; \
-	\
-	dockerd --version; \
-	docker --version
+        aarch64) dockerArch='aarch64' ;; \
+        *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+    esac; \
+    \
+    if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+        echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+        exit 1; \
+    fi; \
+    \
+    tar --extract \
+        --file docker.tgz \
+        --strip-components 1 \
+        --directory /usr/local/bin/ \
+    ; \
+    rm docker.tgz; \
+    \
+    dockerd --version; \
+    docker --version
 
 COPY modprobe.sh /usr/local/bin/modprobe
 COPY docker-entrypoint.sh /usr/local/bin/
